In [89]:
import pandas as pd
import numpy as np 
from tensorflow.keras.layers import Conv2D, Flatten, MaxPool2D, Dense, ZeroPadding2D, Input, Activation, BatchNormalization, Add, GlobalAveragePooling2D
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.optimizers import SGD
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [2]:
from tensorflow.keras.datasets import mnist
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()
print(X_train.shape, X_test.shape, Y_train.shape, Y_test.shape)

(60000, 28, 28) (10000, 28, 28) (60000,) (10000,)


In [3]:
np.random.seed(123)

In [4]:
#### RESHAPING THE TRAIN AND TEST DATA ACCORDING TO THE MODELS REQUIREMENT

X_train = X_train.reshape([-1, 28, 28, 1]).astype('float32')
X_test = X_test.reshape([-1, 28, 28, 1]).astype('float32')

X_train = X_train/255
X_train = X_train

X_test = X_test/255

In [5]:
#### PRINTING THE TRAINING AND TEST LABELS ACCORDING TO THE MODELS REQUIREMENT

from tensorflow.keras.utils import to_categorical

Y_train_cm = Y_train
Y_test_cm = Y_test

Y_train_req = to_categorical(Y_train)
Y_test_req = to_categorical(Y_test)

print(Y_train_cm.shape, Y_test_cm.shape, Y_train_req.shape, Y_test_req.shape)

(60000,) (10000,) (60000, 10) (10000, 10)


<h1>LENET-5 FOR MNIST DATA</h1>

In [6]:
#### CREATING THE MODEL : LENET-5

model = Sequential()
model.add(Conv2D(6, (5,5), strides=1, input_shape=(28,28,1), activation='relu'))
model.add(MaxPool2D((2,2), strides=2))
model.add(Conv2D(16, (5,5), strides=1, activation='relu'))
model.add(MaxPool2D((2,2), strides=2))
model.add(Flatten())
model.add(Dense(120, activation='relu'))
model.add(Dense(84, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [7]:
#### PRINTING THE MODEL SUMMARY

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 24, 24, 6)         156       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 12, 12, 6)         0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 8, 8, 16)          2416      
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 4, 4, 16)          0         
_________________________________________________________________
flatten (Flatten)            (None, 256)               0         
_________________________________________________________________
dense (Dense)                (None, 120)               30840     
_________________________________________________________________
dense_1 (Dense)              (None, 84)                1

In [8]:
#### COMPILING THE MODEL

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [9]:
#### FITTING THE MDOEL

model.fit(X_train, Y_train_req, validation_split=0.1, epochs=15, batch_size=32)

Train on 54000 samples, validate on 6000 samples
Epoch 1/15
54000/54000 [==============================] - 18s 328us/sample - loss: 0.2010 - accuracy: 0.9370 - val_loss: 0.0731 - val_accuracy: 0.9783
Epoch 2/15
54000/54000 [==============================] - 15s 270us/sample - loss: 0.0711 - accuracy: 0.9777 - val_loss: 0.0473 - val_accuracy: 0.9857
Epoch 3/15
54000/54000 [==============================] - 16s 294us/sample - loss: 0.0508 - accuracy: 0.9840 - val_loss: 0.0457 - val_accuracy: 0.9870
Epoch 4/15
54000/54000 [==============================] - 16s 294us/sample - loss: 0.0387 - accuracy: 0.9877 - val_loss: 0.0533 - val_accuracy: 0.9843
Epoch 5/15
54000/54000 [==============================] - 17s 306us/sample - loss: 0.0306 - accuracy: 0.9902 - val_loss: 0.0437 - val_accuracy: 0.9872
Epoch 6/15
54000/54000 [==============================] - 17s 307us/sample - loss: 0.0267 - accuracy: 0.9914 - val_loss: 0.0393 - val_accuracy: 0.9895
Epoch 7/15
54000/54000 [=====================

In [10]:
#### EVALUATING THE LENET-5 MODEL FOR MNIST DATA

model.evaluate(X_test, Y_test_req, batch_size=32)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.05281400087490454, 0.9882]

In [11]:
#### PRINTING THE CONFUSION MATRIX

predictions = model.predict_classes(X_test)
print(confusion_matrix(Y_test_cm, predictions))

[[ 974    1    0    0    0    0    0    2    3    0]
 [   2 1127    1    1    0    0    1    1    2    0]
 [   1    4 1018    2    1    0    0    2    4    0]
 [   0    0    1 1005    0    2    0    0    2    0]
 [   0    1    0    0  972    0    2    2    0    5]
 [   0    0    0   19    0  866    1    1    2    3]
 [   3    3    0    0    1    2  947    0    2    0]
 [   0    4    2    0    2    0    0 1018    1    1]
 [   2    0    1    2    1    0    2    1  963    2]
 [   0    0    0    2    5    4    1    0    5  992]]


<h1>ALEX NET </h1>

In [12]:
#### CREATING THE ALEXNET MODEL

model = Sequential()
model.add(Conv2D(96, (3,3), strides=1, input_shape=(28,28,1), activation='relu'))
model.add(MaxPool2D((3,3), strides=2))
model.add(Conv2D(256, (5,5), padding='same', activation='relu'))
model.add(MaxPool2D((3,3), strides=2))
model.add(Conv2D(384, (3,3), padding='same', activation='relu'))
model.add(Conv2D(384, (3,3), padding='same', activation='relu'))
model.add(Conv2D(256, (3,3), padding='same', activation='relu'))
model.add(MaxPool2D((3,3), strides=2))
model.add(Flatten())
model.add(Dense(4096, activation='relu'))
model.add(Dense(4096, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [13]:
#### PRINTING THE MODEL SUMMARY

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 26, 26, 96)        960       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 12, 12, 96)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 12, 12, 256)       614656    
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 5, 5, 256)         0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 5, 5, 384)         885120    
_________________________________________________________________
conv2d_5 (Conv2D)            (None, 5, 5, 384)         1327488   
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 5, 5, 256)        

In [14]:
#### COMPILING THE MODEL

opt = SGD(lr=1e-4, momentum=0.9)
model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])

In [15]:
#### FITTING THE MODEL

model.fit(X_train, Y_train_req, validation_split=0.1, epochs=20, batch_size=32)

Train on 54000 samples, validate on 6000 samples
Epoch 1/20
54000/54000 [==============================] - 199s 4ms/sample - loss: 2.2928 - accuracy: 0.2882 - val_loss: 2.2809 - val_accuracy: 0.4378
Epoch 2/20
54000/54000 [==============================] - 232s 4ms/sample - loss: 2.2469 - accuracy: 0.5063 - val_loss: 2.1670 - val_accuracy: 0.6157
Epoch 3/20
54000/54000 [==============================] - 223s 4ms/sample - loss: 1.4418 - accuracy: 0.6910 - val_loss: 0.5845 - val_accuracy: 0.8220
Epoch 4/20
54000/54000 [==============================] - 224s 4ms/sample - loss: 0.4279 - accuracy: 0.8735 - val_loss: 0.2455 - val_accuracy: 0.9295
Epoch 5/20
54000/54000 [==============================] - 234s 4ms/sample - loss: 0.2487 - accuracy: 0.9234 - val_loss: 0.1787 - val_accuracy: 0.9468
Epoch 6/20
54000/54000 [==============================] - 242s 4ms/sample - loss: 0.1882 - accuracy: 0.9424 - val_loss: 0.1416 - val_accuracy: 0.9567
Epoch 7/20
54000/54000 [===========================

In [16]:
#### EVALUATING THE MODEL

model.evaluate(X_test, Y_test_req, batch_size=32)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.04592741938894614, 0.9857]

In [17]:
#### PRINTING THE CONFUSION MATRIX

predictions = model.predict_classes(X_test)
print(confusion_matrix(Y_test_cm, predictions))

[[ 968    0    2    0    1    0    2    2    4    1]
 [   0 1131    2    0    0    0    0    2    0    0]
 [   1    2 1024    0    0    0    0    4    1    0]
 [   0    0    3  988    0    4    0    5    9    1]
 [   0    0    0    0  972    0    1    3    2    4]
 [   3    0    0    6    0  871    5    1    4    2]
 [   4    3    0    1    3    1  942    0    4    0]
 [   0    1    8    0    0    0    0 1017    2    0]
 [   4    0    4    1    0    1    0    3  958    3]
 [   3    3    0    3    5    1    0    7    1  986]]


<h1> VGG-16 LIKE MODEL </h1>

In [18]:
model = Sequential()
model.add(Input((28, 28, 1)))
model.add(ZeroPadding2D((2,2)))
model.add(Conv2D(64, (3,3), strides=1, padding='same', activation='relu'))
model.add(Conv2D(64, (3,3), strides=1, padding='same', activation='relu'))
model.add(MaxPool2D((2,2), strides=2))
model.add(Conv2D(128, (3,3), strides=1, padding='same', activation='relu'))
model.add(Conv2D(128, (3,3), strides=1, padding='same', activation='relu'))
model.add(MaxPool2D((2,2), strides=2))
model.add(Conv2D(256, (3,3), strides=1, padding='same', activation='relu'))
model.add(Conv2D(256, (3,3), strides=1, padding='same', activation='relu'))
model.add(Conv2D(256, (3,3), strides=1, padding='same', activation='relu'))
model.add(MaxPool2D((2,2), strides=2))
model.add(Flatten())
model.add(Dense(4096, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [19]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
zero_padding2d (ZeroPadding2 (None, 32, 32, 1)         0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 32, 32, 64)        640       
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 32, 32, 64)        36928     
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 16, 16, 64)        0         
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 16, 16, 128)       73856     
_________________________________________________________________
conv2d_10 (Conv2D)           (None, 16, 16, 128)       147584    
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 8, 8, 128)        

In [20]:
opt = SGD(lr=1e-4, momentum=0.9)
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

In [21]:
model.fit(X_train, Y_train_req, epochs=30, batch_size=32, validation_split=0.1)

Train on 54000 samples, validate on 6000 samples
Epoch 1/30
54000/54000 [==============================] - 197s 4ms/sample - loss: 2.2973 - accuracy: 0.1411 - val_loss: 2.2922 - val_accuracy: 0.1088
Epoch 2/30
54000/54000 [==============================] - 198s 4ms/sample - loss: 2.2826 - accuracy: 0.2839 - val_loss: 2.2658 - val_accuracy: 0.4530
Epoch 3/30
54000/54000 [==============================] - 195s 4ms/sample - loss: 2.0303 - accuracy: 0.5290 - val_loss: 0.7658 - val_accuracy: 0.7920
Epoch 4/30
54000/54000 [==============================] - 190s 4ms/sample - loss: 0.4642 - accuracy: 0.8550 - val_loss: 0.2350 - val_accuracy: 0.9317
Epoch 5/30
54000/54000 [==============================] - 190s 4ms/sample - loss: 0.2411 - accuracy: 0.9237 - val_loss: 0.1700 - val_accuracy: 0.9457
Epoch 6/30
54000/54000 [==============================] - 190s 4ms/sample - loss: 0.1692 - accuracy: 0.9470 - val_loss: 0.1292 - val_accuracy: 0.9633
Epoch 7/30
54000/54000 [===========================

In [22]:
#### EVALUATING THE MODEL

model.evaluate(X_test, Y_test_req, batch_size=32)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.05050676553477242, 0.9847]

In [23]:
#### PRINTING THE CONFUSION MATRIX

predictions = model.predict_classes(X_test)
print(confusion_matrix(Y_test_cm, predictions))

[[ 971    0    1    0    0    2    2    1    3    0]
 [   1 1127    1    0    0    1    2    1    2    0]
 [   4    0 1018    1    1    0    0    3    4    1]
 [   0    0    2  978    0   20    0    1    7    2]
 [   0    0    2    0  975    0    2    2    0    1]
 [   1    0    0    0    1  885    1    0    3    1]
 [   3    2    0    1    1    6  942    0    3    0]
 [   0    1    6    2    1    0    0 1014    1    3]
 [   2    0    1    1    0    5    0    1  962    2]
 [   1    3    0    7   12    3    0    6    2  975]]


<h1> RESIDUAL NETWORK - 18 LAYER</h1>

In [114]:
#### DEFINING THE CONVOLUTION LAYTER

def conv_layer(inputs, filters, stride):
    
    shortcut = inputs
    
    n1, n2 = filters
    
    conv_1 = Conv2D(n1, (3,3), strides=stride, padding='same')(inputs)
    conv_1 = BatchNormalization()(conv_1)
    conv_1 = Activation('relu')(conv_1)
    
    conv_2 = Conv2D(n2, (3,3), strides=1, padding='same')(conv_1)
    conv_2 = BatchNormalization()(conv_2)
    
    short_cut = Conv2D(n2, (3,3), strides=stride, padding='same')(shortcut)
    short_cut = BatchNormalization()(short_cut)
    
    output = Add()([conv_2, short_cut])
    output = Activation('relu')(output)
    
    return output    

In [115]:
#### DEFINING THE IDENTITY LAYER

def identity_layer(inputs, filters):
    
    shortcut = inputs
    
    n1, n2 = filters
        
    conv_1 = Conv2D(n1, (3,3), strides=1, padding='same')(inputs)
    conv_1 = BatchNormalization()(conv_1)
    conv_1 = Activation('relu')(conv_1)
    
    conv_2 = Conv2D(n2, (3,3), strides=1, padding='same')(conv_1)
    conv_2 = BatchNormalization()(conv_2)
    
    output = Add()([conv_2, shortcut])
    output = Activation('relu')(output)
    
    return output    

In [116]:
#### DEFINING THE MODEL 

def ResNet18(input_shape, classes):
    
    inputs = Input(input_shape)
    
    layer_1 = ZeroPadding2D((3,3))(inputs)
    
    conv_1 = Conv2D(64, (7,7), strides=2)(layer_1)
    conv_1 = BatchNormalization()(conv_1)
    conv_1 = Activation('relu')(conv_1)
    conv_1 = ZeroPadding2D((1,1))(conv_1)
    conv_1 = MaxPool2D((3,3), strides=2)(conv_1)
    
    conv_2 = conv_layer(conv_1, [64, 64], stride=1)
    conv_2 = identity_layer(conv_2, [64, 64])
    
    conv_3 = conv_layer(conv_2, [128, 128], stride=2)
    conv_3 = identity_layer(conv_3, [128, 128])
    /
    conv_4 = conv_layer(conv_3, [256, 256], stride=2)
    conv_4 = identity_layer(conv_4, [256, 256])
    
    conv_5 = conv_layer(conv_4, [512, 512], stride=2)
    conv_5 = identity_layer(conv_5, [512, 512])
    
    avg_layer = GlobalAveragePooling2D()(conv_5)
    
    output = Dense(classes, activation='softmax')(avg_layer)
    
    model = Model(inputs=inputs, outputs = output)
    
    return model

In [117]:
#### CALLING THE MODEL

ResNet18 = ResNet18(input_shape=(28, 28, 1), classes=10)

In [118]:
### MODEL SUMMARY

ResNet18.summary()

Model: "model_11"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_25 (InputLayer)           [(None, 28, 28, 1)]  0                                            
__________________________________________________________________________________________________
zero_padding2d_45 (ZeroPadding2 (None, 34, 34, 1)    0           input_25[0][0]                   
__________________________________________________________________________________________________
conv2d_211 (Conv2D)             (None, 14, 14, 64)   3200        zero_padding2d_45[0][0]          
__________________________________________________________________________________________________
batch_normalization_195 (BatchN (None, 14, 14, 64)   256         conv2d_211[0][0]                 
___________________________________________________________________________________________

In [119]:
#### COMPILING THE MODEL

opt = SGD(lr=1e-4, momentum=0.9)
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

In [120]:
#### FITTING THE MODEL

model.fit(X_train, Y_train_req, epochs=20, batch_size=32, validation_split=0.1)

Train on 54000 samples, validate on 6000 samples
Epoch 1/20
54000/54000 [==============================] - 118s 2ms/sample - loss: 0.2384 - accuracy: 0.9246 - val_loss: 0.0675 - val_accuracy: 0.9797
Epoch 2/20
54000/54000 [==============================] - 138s 3ms/sample - loss: 0.0691 - accuracy: 0.9782 - val_loss: 0.0575 - val_accuracy: 0.9832
Epoch 3/20
54000/54000 [==============================] - 191s 4ms/sample - loss: 0.0428 - accuracy: 0.9859 - val_loss: 0.0473 - val_accuracy: 0.9858
Epoch 4/20
54000/54000 [==============================] - 213s 4ms/sample - loss: 0.0285 - accuracy: 0.9911 - val_loss: 0.0467 - val_accuracy: 0.9865
Epoch 5/20
54000/54000 [==============================] - 189s 4ms/sample - loss: 0.0176 - accuracy: 0.9949 - val_loss: 0.0447 - val_accuracy: 0.9870
Epoch 6/20
54000/54000 [==============================] - 188s 3ms/sample - loss: 0.0125 - accuracy: 0.9965 - val_loss: 0.0436 - val_accuracy: 0.9878
Epoch 7/20
54000/54000 [===========================

In [121]:
#### EVALUATING THE MODEL

model.evaluate(X_test, Y_test_req, batch_size=32)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.03895506707870809, 0.9904]